---

- hosts: homeserver

  vars:
    application: actualbudget

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user_id }}"
        group: "{{ common_group_id }}"
        mode: "0771"

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: ghcr.io/actualbudget/actual:26.2.1
        env:
          ACTUAL_OPENID_DISCOVERY_URL: "{{ oidc_discovery_url }}"
          ACTUAL_OPENID_CLIENT_ID: "{{ application }}"
          ACTUAL_OPENID_CLIENT_SECRET: "{{ oidc_auth.actualbudget.secret }}"
          ACTUAL_OPENID_SERVER_HOSTNAME: "https://{{ application }}.{{ common_tld }}"
          ACTUAL_OPENID_ENFORCE: "true"
        volumes:
          - "{{ config_directory }}:/data"
        traefik:
          - port: 5006
        homepage:
          name: Actual Budget
          group: Favourites
          weight: 900
          description: "Budgeting"
        blackbox:
          path: /health
