---

- hosts: homeserver

  vars:
    application: borgmatic

    config_directory: /borgmatic

    borgmatic_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37626530363533323433633066656632393664313962366264363435386635346634613433303661
      3866616565383433353636356337356438373934373433650a653235663033383330386638303031
      63303930626431656232343336393965343966653330323964313532353964613030643137616363
      3966623038626139300a666265326566373439663038393432396432356636353733643361623031
      35663138313039623361346562346234636365316164636365663439326663643261643438376334
      3361306465303461613739396564306434333033643962616664

    borgmatic_notification_webhook_id: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36333864613836636138376164353330343661636439653564363232336434663563343139366665
      3036663462353966316463666236373131666632666531380a356638653163323734343466656565
      30373435623231616465303664353630336338663361373032636266663961366364313436386338
      3661323238613131330a303061306332306262646165376564306338326635643766356364643136
      33323734393461663237663339336365333566316164613939383064386266666461

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create Borgmatic directories
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user_id }}"
        group: "{{ common_root_group }}"
        mode: "0771"

    - name: Clone Borgbackup repo
      ansible.builtin.git:
        repo: https://github.com/borgbackup/borg
        clone: true
        dest: "{{ config_directory }}/borgbackup"
        version: "1.4.3"

    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ config_directory }}/{{ item.0.name }}/{{ item.1 }}"
        state: directory
        mode: "0744"
      with_nested:
        - "{{ borgmatic_backups }}"
        - ["borgmatic", "config/borg", "borgmatic.d", "ssh", "cache/borg"]

    - name: "Template configuration"
      ansible.builtin.template:
        src: "{{ files_directory }}/config.yaml.j2"
        dest: "{{ config_directory }}/{{ item.name }}/borgmatic.d/config.yaml"
        owner: root
        group: root
        mode: "0744"
      loop: "{{ borgmatic_backups }}"

    - name: "Template crontab"
      ansible.builtin.copy:
        content: "{{ item.crontab }} /usr/local/bin/borgmatic --stats --list -v 0 2>&1"
        dest: "{{ config_directory }}/{{ item.name }}/borgmatic.d/crontab.txt"
        owner: root
        group: root
        mode: "0755"
      loop: "{{ borgmatic_backups }}"

    - name: Copy SSH files
      ansible.builtin.copy:
        src: "{{ files_directory }}/ssh/"
        dest: "{{ config_directory }}/ssh/"
        owner: root
        group: root
        mode: "0600"

    - name: Add servers to known hosts
      ansible.builtin.known_hosts:
        path: "{{ config_directory }}/ssh/known_hosts"
        name: "[{{ item.hostname }}]:{{ item.port }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t ed25519 -p ' + (item.port | string) + ' ' + item.hostname + ' 2>/dev/null | grep ssh-ed25519') }}"
      loop: "{{ borg_servers }}"

    - name: Template notification script
      ansible.builtin.template:
        src: "{{ files_directory }}/notifications.sh.j2"
        dest: "{{ config_directory }}/{{ item.name }}/borgmatic.d/notifications.sh"
        mode: "0500"
      loop: "{{ borgmatic_backups }}"

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        container_name: "borgmatic-{{ item.name }}"
        image: ghcr.io/borgmatic-collective/borgmatic:2.1.0
        env:
          TZ: "{{ common_timezone }}"
          BORG_PASSPHRASE: "{{ borgmatic_pass }}"
          BORG_CHECK_I_KNOW_WHAT_I_AM_DOING: "YES"
          BORG_RELOCATED_REPO_ACCESS_IS_OK: "yes"
        volumes:
          # data to backup. mount as rw when a restore is needed
          - "{{ item.source }}:/mnt/source:ro"

          - "{{ config_directory }}/borgbackup:/mnt/borg-repository"
          - "{{ config_directory }}/ssh:/root/.ssh"

          - "{{ config_directory }}/{{ item.name }}/borgmatic.d/:/etc/borgmatic.d/"
          - "{{ config_directory }}/{{ item.name }}/borgmatic:/root/.borgmatic"
          - "{{ config_directory }}/{{ item.name }}/config/borg:/root/.config/borg"
          - "{{ config_directory }}/{{ item.name }}/cache/borg:/root/.cache/borg"
      loop: "{{ borgmatic_backups }}"

    - name: Initialise repos
      containers.podman.podman_container_exec:
        name: "borgmatic-{{ item.name }}"
        command: borgmatic repo-create --encryption=repokey-blake2
      register: _command_result
      changed_when: _command_result.stdout != ''
      loop: "{{ borgmatic_backups }}"

    - name: Disable older versions for security
      containers.podman.podman_container_exec:
        name: "borgmatic-{{ item.name }}"
        command: borgmatic borg upgrade --disable-tam
      register: _command_result
      changed_when: _command_result.stdout != ''
      loop: "{{ borgmatic_backups }}"
