---

- hosts: homeserver

  vars:
    application: fitbit-activity-generator

    fitbit_accounts:
      - calvin
      - tammy
      - michaelf

    container_network: "{{ networks.guest }}"

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Check if token exists
      ansible.builtin.stat:
        path: "{{ config_directory }}/{{ item }}.json"
      register: _fitbit_token_stat
      loop: "{{ fitbit_accounts }}"

    - name: Ensure token exists
      ansible.builtin.fail:
        msg: "A token file is missing!"
      when: not item.stat.exists
      loop: "{{ _fitbit_token_stat.results }}"

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        container_name: "{{ application }}-{{ item }}"
        image: ghcr.io/calvinbui/fitbit-activity-generator:v2.0.0
        env:
          INTERVAL: "120"
          TZ: "{{ common_timezone }}"
          TOKEN_PATH: /usr/src/app/token.json
        volumes:
          - "{{ config_directory }}/{{ item }}.json:/usr/src/app/token.json:rw"
      loop: "{{ fitbit_accounts }}"
