---

- hosts: homeserver

  vars:
    application: glances

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: docker.io/nicolargo/glances:ubuntu-4.5.0.5-full
        pid_mode: host
        env:
          GLANCES_OPT: "-w"
          TZ: "{{ common_timezone }}"
        volumes:
          - /run/podman/podman.sock:/var/run/docker.sock:ro
          - /etc/os-release:/etc/os-release:ro
        traefik:
          - port: 61208
            auth: page
        blackbox:
          path: /api/4/status
        homepage:
          group: Monitoring
          weight: 250
          description: "System monitoring"
          widget:
            metric: info
            version: 4
