---

# https://wiki.debian.org/NetworkInterfaceNames#CUSTOM_SCHEMES_USING_.LINK_FILES
# https://manpages.debian.org/trixie/systemd/systemd.netdev.5.en.html
# https://manpages.debian.org/trixie/systemd/systemd.network.5.en.html

- hosts: homeserver

  vars:
    network_interface:
      name: fiber1
      mac: ec:0d:9a:8b:33:d4

  handlers:
    - name: Regenerate the kernel initramfs
      ansible.builtin.command: update-initramfs -u
      changed_when: true

    - name: Restart systemd-networkd
      ansible.builtin.service:
        name: systemd-networkd
        state: restarted

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 360

  tasks:
    # `systemd-networkd` sets what DNS servers to use, but it doesn’t actually do DNS lookups.
    # `systemd-resolved` is the resolver that reads those DNS servers and answers queries.
    # Without `systemd-resolved`, nothing updates /etc/resolv.conf, so it stays empty.
    # `libnss-resolve` plugs systemd-resolved into /etc/nsswitch.conf, so apps actually use it.
    - name: Install DNS resolver
      ansible.builtin.apt:
        name: systemd-resolved
        state: present
        update_cache: true
        cache_valid_time: 86400

    # doesn't auto-start by default on many distros because they use a different service for network management
    - name: Enable systemd-networkd to start at boot
      ansible.builtin.service:
        name: systemd-networkd
        enabled: true

    - name: Create systemd .link files for interface renaming
      ansible.builtin.copy:
        content: |
          [Match]
          MACAddress={{ network_interface.mac }}

          [Link]
          Name={{ network_interface.name }}
        dest: "/etc/systemd/network/10-{{ network_interface.name }}.link"
        mode: "0644"
      notify:
        - Regenerate the kernel initramfs
        - Reboot

    - name: Configure interface network
      ansible.builtin.copy:
        content: |
          [Match]
          Name={{ network_interface.name }}

          [Network]
          LinkLocalAddressing=no
          DHCP=no
          {% for network in networks.values() %}
          {% if 'vlan' in network %}
          VLAN=vlan{{ network.vlan }}
          {% endif %}
          {% endfor %}
        dest: "/etc/systemd/network/30-{{ network_interface.name }}.network"
        mode: "0644"
      notify:
        - Restart systemd-networkd

    - name: Create VLAN networks
      ansible.builtin.copy:
        content: |
          [NetDev]
          Name=vlan{{ item.value.vlan }}
          Kind=vlan

          [VLAN]
          Id={{ item.value.vlan }}
        dest: "/etc/systemd/network/40-vlan{{ item.value.vlan }}.netdev"
        mode: "0644"
      loop: "{{ networks | ansible.builtin.dict2items }}"
      when: item.value.vlan is defined
      notify:
        - Restart systemd-networkd

    - name: Configure VLAN networks
      ansible.builtin.copy:
        content: |
          [Match]
          Name=vlan{{ item.value.vlan }}

          [Network]
          DHCP={{ "yes" if item.value.name == "mgmt" else "no" }}
          LinkLocalAddressing=no
        dest: "/etc/systemd/network/60-vlan{{ item.value.vlan }}.network"
        mode: "0644"
      loop: "{{ networks | ansible.builtin.dict2items }}"
      when: item.value.vlan is defined
      notify:
        - Restart systemd-networkd
