---

- hosts: homeserver

  vars:
    application: nzbget

    container_network: "{{ networks.pub }}"

  handlers:
    - name: Restart
      containers.podman.podman_container:
        name: "{{ application }}"
        force_restart: true

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_root_group }}"
        mode: "0771"

    - name: Create unpack pass file
      ansible.builtin.copy:
        content: |
          404
        dest: "{{ config_directory }}/unpackpassfile.txt"
        owner: "{{ common_user_id }}"
        group: "{{ common_root_group }}"
        mode: "0644"

    - name: Create scripts folder
      ansible.builtin.file:
        path: "{{ config_directory }}/scripts"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_root_group }}"
        mode: "0771"

    - name: Clone ExtendedUnpacker
      ansible.builtin.git:
        repo: https://github.com/nzbgetcom/Extension-ExtendedUnpacker.git
        dest: "{{ config_directory }}/scripts/extendedunpacker"
        force: true
        update: true

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: ghcr.io/nzbgetcom/nzbget:v26.0
        stop_signal: "{{ signal_map['SIGKILL'] }}"
        env:
          PUID: "{{ common_user_id | ansible.builtin.string }}"
          PGID: "{{ common_root_group | ansible.builtin.string }}"
          TZ: "{{ common_timezone }}"
        volumes:
          - "{{ config_directory }}:/config"
          - "{{ common_directory_download }}:{{ common_mounted_directory_download }}"
        traefik:
          -
            port: 6789
            auth: page
            rule: Host(`{{ application }}.{{ common_tld }}`)
          -
            name: "{{ application }}-bypass-auth"
            port: 6789
            rule: Host(`{{ application }}.{{ common_tld }}`) && Header(`{{ traefik_bypass_auth_header.key }}`, `{{ traefik_bypass_auth_header.value }}`)
        homepage:
          name: NZBGet
          group: Favourites
          weight: 200
          description: "Download files from Usenet"
          widget:
            username: ""
            password: ""

    - name: Wait for config
      ansible.builtin.wait_for:
        path: "{{ config_directory }}/nzbget.conf"

    - name: Configure
      ansible.builtin.lineinfile:
        dest: "{{ config_directory }}/nzbget.conf"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      loop: "{{ nzbget_config | ansible.builtin.dict2items }}"
      notify: Restart
      vars:
        nzbget_config:
          # PATHS
          MainDir: "{{ common_mounted_directory_download }}"
          DestDir: '${MainDir}'
          InterDir: '${MainDir}/Intermediate/Incomplete'
          NzbDir: '${MainDir}/Intermediate/Watch'
          QueueDir: '${MainDir}/Intermediate/Queue'
          TempDir: '${MainDir}/Intermediate/Temp'
          WebDir: '${AppDir}/webui'
          ScriptDir: '/config/scripts'
          LockFile: '/config/nzbget.lock'
          LogFile: '/config/nzbget.log'
          ConfigTemplate: '${AppDir}/webui/nzbget.conf.template'

          # NEWS-SERVERS
          Server1.Active: 'yes'
          Server1.Name: 'Frugal AU'
          Server1.Level: '0'
          Server1.Optional: 'no'
          Server1.Group: '1'
          Server1.Host: 'aunews.frugalusenet.com'
          Server1.Port: '563'
          Server1.Username: &frugal_username !vault |
            $ANSIBLE_VAULT;1.1;AES256
            39613066303661343361373534393963666466396339636235373837396232343265653864336464
            6531303835346466616238353531393136356466373438320a626139353564313038303339393634
            38633038356637393333383664636430386536666635353064373062613863383366313139613066
            3934616136333433350a323663313161383963613239646462643632343530633032323136393031
            6139
          Server1.Password: &frugal_password !vault |
            $ANSIBLE_VAULT;1.1;AES256
            37316362333639636564326637363365356439303536323033353634633263303739383264643936
            3265623431323161333137353935656536666362306339650a323330623464396562343436633033
            33613061666666656135616161656337663731333232353339383538363739613461613663353431
            3831646534393635390a326537643464353664376631333131616231626436323564316335393662
            36393936343636353765653965666532383233396561653664336362316465653531
          Server1.JoinGroup: 'no'
          Server1.Encryption: 'yes'
          Server1.Cipher: 'AES128-SHA'
          Server1.Connections: '100'
          Server1.Retention: '5500'
          Server1.IpVersion: 'ipv4'
          Server1.Notes: ''

          Server2.Active: 'yes'
          Server2.Name: 'Frugal US East'
          Server2.Level: '1'
          Server2.Optional: 'no'
          Server2.Group: '1'
          Server2.Host: 'news.frugalusenet.com'
          Server2.Port: '563'
          Server2.Username: *frugal_username
          Server2.Password: *frugal_password
          Server2.JoinGroup: 'no'
          Server2.Encryption: 'yes'
          Server2.Cipher: 'AES128-SHA'
          Server2.Connections: '50'
          Server2.Retention: '5500'
          Server2.IpVersion: 'ipv4'
          Server2.Notes: ''

          Server3.Active: 'yes'
          Server3.Name: 'Frugal EU'
          Server3.Level: '1'
          Server3.Optional: 'no'
          Server3.Group: '1'
          Server3.Host: 'eunews.frugalusenet.com'
          Server3.Port: '563'
          Server3.Username: *frugal_username
          Server3.Password: *frugal_password
          Server3.JoinGroup: 'no'
          Server3.Encryption: 'yes'
          Server3.Cipher: 'AES128-SHA'
          Server3.Connections: '50'
          Server3.Retention: '5500'
          Server3.IpVersion: 'ipv4'
          Server3.Notes: ''

          Server4.Active: 'yes'
          Server4.Name: 'Frugal Bonus'
          Server4.Level: '2'
          Server4.Optional: 'no'
          Server4.Group: '2'
          Server4.Host: 'bonus.frugalusenet.com'
          Server4.Port: '563'
          Server4.Username: *frugal_username
          Server4.Password: *frugal_password
          Server4.JoinGroup: 'no'
          Server4.Encryption: 'yes'
          Server4.Cipher: 'AES128-SHA'
          Server4.Connections: '50'
          Server4.Retention: '3000'
          Server4.IpVersion: 'ipv4'
          Server4.Notes: ''

          Server5.Active: 'yes'
          Server5.Name: 'Frugal US West'
          Server5.Level: '3'
          Server5.Optional: 'no'
          Server5.Group: '1'
          Server5.Host: 'newswest.frugalusenet.com'
          Server5.Port: '563'
          Server5.Username: *frugal_username
          Server5.Password: *frugal_password
          Server5.JoinGroup: 'no'
          Server5.Encryption: 'yes'
          Server5.Cipher: 'AES128-SHA'
          Server5.Connections: '50'
          Server5.Retention: '5500'
          Server5.IpVersion: 'ipv4'
          Server5.Notes: ''

          Server6.Active: 'yes'
          Server6.Name: 'Frugal Brazil'
          Server6.Level: '3'
          Server6.Optional: 'no'
          Server6.Group: '1'
          Server6.Host: 'sanews.frugalusenet.com'
          Server6.Port: '563'
          Server6.Username: *frugal_username
          Server6.Password: *frugal_password
          Server6.JoinGroup: 'no'
          Server6.Encryption: 'yes'
          Server6.Cipher: 'AES128-SHA'
          Server6.Connections: '100'
          Server6.Retention: '5500'
          Server6.IpVersion: 'ipv4'
          Server6.Notes: ''

          Server7.Active: 'yes'
          Server7.Name: 'Frugal Japan'
          Server7.Level: '3'
          Server7.Optional: 'no'
          Server7.Group: '1'
          Server7.Host: 'asnews.frugalusenet.com'
          Server7.Port: '563'
          Server7.Username: *frugal_username
          Server7.Password: *frugal_password
          Server7.JoinGroup: 'no'
          Server7.Encryption: 'yes'
          Server7.Cipher: 'AES128-SHA'
          Server7.Connections: '100'
          Server7.Retention: '5500'
          Server7.IpVersion: 'ipv4'
          Server7.Notes: ''

          Server8.Active: 'yes'
          Server8.Name: 'Newshosting'
          Server8.Level: '0'
          Server8.Optional: 'no'
          Server8.Group: '0'
          Server8.Host: 'news.newshosting.com'
          Server8.Port: '563'
          Server8.Username: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            30306564633339636335336138393132306637346432333337366339386633613235336530306261
            6138343664313938663863356237336332623538626632340a393035346336336532643139376362
            64633835353163383639323435666433393935323238623662303861376335383864663562313639
            3533636333306534640a633438633638643366306164613966343463636161653931323762346134
            3365
          Server8.Password: &newshosting_password !vault |
            $ANSIBLE_VAULT;1.1;AES256
            32663037346262623437326463643162316566313135373532653566653365316366643762386630
            3539323762363564643936613265333161376639376462310a366637666466326238306332376337
            37323565373932623666616530323466343230353330623332663634346433383965653935333034
            3336643862383239300a646465653933346561646362633163323230336565356238313465613833
            38633136616465643736363432616661643663323662363931636134383430333666
          Server8.JoinGroup: 'no'
          Server8.Encryption: 'yes'
          Server8.Cipher: 'AES128-SHA'
          Server8.Connections: '100'
          Server8.Retention: '5950'
          Server8.IpVersion: 'ipv4'
          Server8.Notes: ''

          Server9.Active: 'yes'
          Server9.Name: 'Blocknews US'
          Server9.Level: '2'
          Server9.Optional: 'no'
          Server9.Group: '0'
          Server9.Host: 'usnews.blocknews.net'
          Server9.Port: '563'
          Server9.Username: &blocknews_username !vault |
            $ANSIBLE_VAULT;1.1;AES256
            62663232306238393433666262366163343837373638633365643734313030646337393863306630
            6265386262356261333531356565346134343638633731320a613863633236386661363638353561
            65623136663161613335383764653233366462366539313734303635353566363331623733643736
            3261353936303336620a656235623765376136623238613765613630656262366632383939313435
            3839
          Server9.Password: &blocknews_password !vault |
            $ANSIBLE_VAULT;1.1;AES256
            34396362353562643230303564663732353735366662326366336664636665626263336130306364
            3965393063626433363335353231306666303666636564300a613131373565343364386338396537
            39353366343737373830643932613737643238343438623530613936633034613034316431326666
            3538623233303930350a346637656361616436323063333235383361353331656232353735396564
            38643661353262383031323966363039353534363032666530336563393035393266
          Server9.JoinGroup: 'no'
          Server9.Encryption: 'yes'
          Server9.Cipher: 'AES128-SHA'
          Server9.Connections: '100'
          Server9.Retention: '5186'
          Server9.IpVersion: 'ipv4'
          Server9.Notes: ''

          Server10.Active: 'yes'
          Server10.Name: 'Blocknews EU'
          Server10.Level: '2'
          Server10.Optional: 'no'
          Server10.Group: '0'
          Server10.Host: 'eunews.blocknews.net'
          Server10.Port: '563'
          Server10.Username: *blocknews_username
          Server10.Password: *blocknews_password
          Server10.JoinGroup: 'no'
          Server10.Encryption: 'yes'
          Server10.Cipher: 'AES128-SHA'
          Server10.Connections: '100'
          Server10.Retention: '5186'
          Server10.IpVersion: 'ipv4'
          Server10.Notes: ''

          # SECURITY
          ControlUsername: ''
          ControlPassword: ''
          UMask: '022'

          # CATEGORIES
          Category1.Name: 'Movies'
          Category1.DestDir: 'Movies'
          Category1.Aliases: 'movies*'
          Category2.Name: 'TV'
          Category2.DestDir: 'TV'
          Category2.Unpack: 'yes'
          Category3.Name: 'Games'
          Category3.DestDir: 'Games'
          Category3.Aliases: 'Games'
          Category4.Name: 'Books'
          Category4.DestDir: 'Books'
          Category4.Aliases: 'Books'
          Category5.Name: 'Anime'
          Category5.DestDir: 'Anime'
          Category5.Unpack: 'yes'

          # INCOMING NZBS
          DupeCheck: 'no'

          # DOWNLOAD QUEUE
          FlushQueue: 'no'
          ContinuePartial: 'no'
          ArticleCache: '500'
          WriteBuffer: '1024'
          PostStrategy: 'rocket'

          # LOGGING
          WriteLog: 'rotate'

          # CHECK AND REPAIR
          CrcCheck: 'yes'
          ParCheck: 'auto'
          ParQuick: 'yes'
          ParBuffer: '8192'
          DirectRename: 'yes'
          ParPauseQueue: 'no'

          # UNPACK
          DirectUnpack: 'yes'
          UnpackPauseQueue: 'no'
          UnrarCmd: '${AppDir}/unrar'
          SevenZipCmd: '${AppDir}/7za'
          UnpackPassFile: '/config/unpackpassfile.txt'

          # EXTENSION SCRIPTS
          Extensions: 'ExtendedUnpacker'
          ScriptOrder: 'ExtendedUnpacker'
          ScriptPauseQueue: 'yes'

          # EXTENDED UNPACKER
          ExtendedUnpacker:UnrarCmd: 'unrar'
          ExtendedUnpacker:UnrarArgs: 'e -idp -ai -o-'
          ExtendedUnpacker:SevenZipCmd: '7z'
          ExtendedUnpacker:SevenZipArgs: 'e -aos'
          ExtendedUnpacker:WaitTime: '0'
          ExtendedUnpacker:DeleteLeftover: 'yes'
