---

- hosts: localhost

  become: false

  connection: local

  force_handlers: true

  gather_facts: false

  vars:
    opnsense_wireguard_vpn:
      -
        interface: "{{ networks.vpn_windscribe_sydney.opnsense_identifier }}"

        provider: windscribe
        location: sydney

        server:
          private_key: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31313331343961633962313264623733366362323365376333613463633463363939366464316461
            6462323835646363306663356234306639326665326464300a353535303966663263613037643538
            30393061643866363561353938353832333237656561626361373030353039343034656339663235
            6135363934383831320a386336373134306330366638323439313565393038316264386438633139
            34326339303261353162323733633837313134303036613331613035366466656639656133616233
            3766303463623037313665633161633934613962363965323735
          address: 100.83.42.92
          gateway: 10.255.255.1

        peer:
          public_key: jCi1I5HBTtwCblBbMzOFmOOFNG1GilYOZgst0kyq9gY=
          endpoint: syd-226-wg.whiskergalaxy.com
          port: 443
          psk: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            65623333373831373233663364633431623136313839353565653830336236623636393533653866
            3337306361396632643835393765626365616662323736310a323835303239356262643235653065
            30323736616332623466636435346439663232376633363263653662646136663137393939623230
            6635326566376436640a303431616430313234323936643033306364616233623934326463346535
            63626561616532313333393061663930393866663137326266303862386364646333363438333933
            6535363861313635353635336364393263353032313863613635

        monitor_ip: 10.255.255.1

        used_by:
          - "{{ networks.iot.opnsense_identifier }}"
          - "{{ networks.pub.opnsense_identifier }}"

  module_defaults:
    group/oxlorg.opnsense.all: "{{ oxlorg_opnsense_module_defaults }}"
    oxlorg.opnsense.rule:
      match_fields: ["interface", "description"]

  handlers:
    - name: Reload firewall rules
      oxlorg.opnsense.reload:
        target: rule

  tasks:
    - name: WireGuard - Derive VPN Public Keys
      ansible.builtin.command:
        argv:
          - wg
          - pubkey
        stdin: "{{ item.server.private_key }}"
      register: _wireguard_vpn_public_keys
      changed_when: false
      check_mode: false
      no_log: true
      loop: "{{ opnsense_wireguard_vpn }}"

    - name: WireGuard - Home Instance
      oxlorg.opnsense.wireguard_server:
        name: Home
        public_key: LyOL+HkCzjVUGMoeSoYt2oLUO5Vu8SGUoguMtMcqxHg=
        private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323235356335343663633631663166633632373532633166353333343162626437663262626234
          6138393932356430636139316538326336303338313061330a363837383533613230386534363563
          62313864316166373061636334646534326266383234666661666133363435613234323135643732
          3632376534656539640a626530633839376566666365623930306331616564343033623535653031
          62663963373334326261313638363539653363346463633035313838303037613463376336643836
          3735363738356534393261303962626562393463643331666336
        port: 51820
        tunnel_address: "{{ networks.vpn_home.subnet }}"
        link_peers: false

    - name: WireGuard - VPN Instance
      oxlorg.opnsense.wireguard_server:
        name: "{{ item.provider }}-{{ item.location }}"
        private_key: "{{ item.server.private_key }}"
        public_key: "{{ _wireguard_vpn_public_keys.results[ansible_loop.index0].stdout }}"
        port: "{{ 51820 + ansible_loop.index }}"
        mtu: 1420
        tunnel_address: "{{ item.server.address }}/32"
        link_peers: false
        disable_routes: true
        gateway: "{{ item.server.gateway }}"
      loop: "{{ opnsense_wireguard_vpn }}"
      loop_control:
        extended: true

    - name: WireGuard - Peers
      oxlorg.opnsense.wireguard_peer:
        name: "{{ item.provider }}-{{ item.location }}"
        public_key: "{{ item.peer.public_key }}"
        endpoint: "{{ item.peer.endpoint }}"
        port: "{{ item.peer.port }}"
        allowed_ips: ["0.0.0.0/0"]
        keepalive: "{{ item.peer.keepalive | default(omit) }}"
        link_servers: true
        servers: ["{{ item.provider }}-{{ item.location }}"]
        psk: "{{ item.peer.psk | default(omit) }}"
      loop: "{{ opnsense_wireguard_vpn }}"

    # An interface needs to be assigned and enabled manually for this step (API doesn't exist for that yet)
    # Also set the MSS on the interface to 1380

    - name: WireGuard - Gateway
      oxlorg.opnsense.gateway:
        name: "VPN_{{ item.provider | ansible.builtin.upper }}_{{ item.location | ansible.builtin.upper }}"
        interface: "{{ item.interface }}"
        ip_protocol: inet
        gateway: "{{ item.monitor_ip }}"
        default_gw: false
        far_gw: true
        monitor_disable: false
        monitor: "{{ item.monitor_ip }}"
        match_fields:
          - name
        priority: 255
      loop: "{{ opnsense_wireguard_vpn }}"

    - name: WireGuard - Firewall Rule
      oxlorg.opnsense.rule:
        sequence: 400
        quick: false
        interface: []
        direction: in
        action: pass
        source_net: "{{ item.interface }}"
        destination_net: "{{ item.interface }}ip"
        gateway: "VPN_{{ item.provider | ansible.builtin.upper }}_{{ item.location | ansible.builtin.upper }}"
        log: true
        allow_opts: true
        description: "VPN_{{ item.provider | ansible.builtin.upper }}_{{ item.location | ansible.builtin.upper }}"
      loop: "{{ opnsense_wireguard_vpn }}"
      notify: Reload firewall rules

    # - name: WireGuard - Next steps
    #   ansible.builtin.debug:
    #     msg:
    #       - Need to be done manually as the API doesn't exist
    #       - 1. Add NAT Outbound - https://opnsense-web.{{ common_local_tld }}/firewall_nat_out.php

    # - name: WireGuard - Add NAT rule
    #   oxlorg.opnsense.nat_source:
    #     interface: "{{ item.interface }}"
    #     source: "opt1"
    #     target: any
    #     description: "VPN_{{ item.provider | ansible.builtin.upper }}"
    #     match_fields: ["description"]
    #   loop: "{{ opnsense_wireguard_vpn }}"
