---

- hosts: opnsense

  tasks:
    - name: Set authorized keys from GitHub
      ansible.builtin.include_role:
        name: github_authorized_keys
      vars:
        github_authorized_keys_users:
          - root
