---

- hosts: homeserver

  vars:
    application: stirlingpdf

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_root_group }}"
        mode: "0771"

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: ghcr.io/stirling-tools/stirling-pdf:2.4.5-fat
        env:
          DOCKER_ENABLE_SECURITY: "true"
          INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
          LANGS: "{{ common_language_iso_639 }}_{{ common_country_iso_3166 }}"

          SECURITY_INITIALLOGIN_USERNAME: "{{ common_user }}"
          SECURITY_INITIALLOGIN_PASSWORD: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            32356265373930643935633934313033393930376636336366636438356239386239353831653334
            6139316461303630373363306531643735643331363830390a666437613031343930366130323830
            63346433313630656365306334613134373437313737363631663737303765343364386566666363
            3861323866643035330a646663653636383934653432393964613831343532643430383830623433
            61303662633164626636643139326432383130663663613265333339653964353636613632386530
            3862383266636635386236633062633737333062326539643434

          SECURITY_ENABLELOGIN: "true"
          SECURITY_LOGINMETHOD: "oauth2"
          SECURITY_OAUTH2_ENABLED: "true"
          SECURITY_OAUTH2_ISSUER: "{{ oidc_base_url }}"
          SECURITY_OAUTH2_AUTOCREATEUSER: "true"
          SECURITY_OAUTH2_CLIENTID: "{{ application }}"
          SECURITY_OAUTH2_CLIENTSECRET: "{{ oidc_auth.stirlingpdf.secret }}"
          SECURITY_OAUTH2_USEASUSERNAME: "preferred_username"
          SECURITY_OAUTH2_SCOPES: "openid,profile,email"
          SECURITY_OAUTH2_PROVIDER: "{{ oidc_provider | ansible.builtin.title }}"

          SYSTEM_DEFAULTLOCALE: "{{ common_language_iso_639 }}-{{ common_country_iso_3166 }}"
          SYSTEM_SHOWUPDATE: "false"

          SYSTEM_ENABLEANALYTICS: "false"
          SYSTEM_ENABLEPOSTHOG: "false"
          SYSTEM_ENABLESCARF: "false"

          ALLOW_GOOGLE_VISIBILITY: "false"

          METRICS_ENABLED: "false"
        volumes:
          - "{{ config_directory }}/trainingData:/usr/share/tessdata"
          - "{{ config_directory }}/extraConfigs:/configs"
        traefik:
          - port: 8080
        blackbox:
          path: /login
        homepage:
          name: Stirling PDF
          group: Documents
          weight: 600
          description: Manage PDF files
