---

- hosts: homeserver

  vars:
    application: tautulli

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_root_group }}"
        mode: "0771"

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: ghcr.io/tautulli/tautulli:v2.16.1
        env:
          PUID: "{{ common_user_id | ansible.builtin.string }}"
          PGID: "{{ common_root_group | ansible.builtin.string }}"
          TZ: "{{ common_timezone }}"
        volumes:
          - "{{ config_directory }}:/config"
        traefik:
          - port: 8181
        homepage:
          group: Plex
          weight: 690
          description: "Plex monitoring and tracking"
          widget:
            key: "{{ tautulli_api_key }}"
        blackbox:
          path: /status
