---

- hosts: homeserver

  vars:
    application: traefik

    container_network: "{{ networks.mgmt }}"

  handlers:
    - name: Restart
      containers.podman.podman_container:
        name: "{{ application }}"
        force_restart: true

  tasks:
    - name: Create logs folder
      ansible.builtin.file:
        path: "{{ config_directory }}/logs"
        state: directory
        owner: "{{ common_user }}"
        group: "root"
        mode: "0771"

    - name: Create acme.json
      ansible.builtin.file:
        path: "{{ config_directory }}/acme.json"
        state: touch
        mode: "0600"
        modification_time: "preserve"
        access_time: "preserve"

    - name: Template traefik configs
      ansible.builtin.template:
        src: "{{ files_directory }}/{{ item }}.j2"
        dest: "{{ config_directory }}/{{ item }}"
        mode: "0440"
      loop:
        - traefik.yaml
        - dynamic_conf.yaml
      notify: Restart

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: public.ecr.aws/docker/library/traefik:v3.6.15
        ip: "{{ traefik_ip }}"
        restart_policy: always
        env:
          CF_DNS_API_TOKEN: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            66373362346536303261353736383938313862303964376463616338393434643132353334386135
            3261653762313738656161373764346533366562343333610a336633623033313364656239386236
            30646464336665636661643735326361633262393634333264323234623964373532376537336130
            3163356662636535360a316237353230336462376638626338363765363262303665303238333863
            33393836303038363631336661643935343335663663396265386333643561636535656237366138
            33623661633764353865306466343565343334353366376139323332386130643663353163633035
            653364333731306463633365326330393735

          TZ: "{{ common_timezone }}"
        volumes:
          - /run/podman/podman.sock:/var/run/docker.sock

          - "{{ config_directory }}/traefik.yaml:/etc/traefik/traefik.yaml"
          - "{{ config_directory }}/acme.json:/acme.json"
          - "{{ config_directory }}/dynamic_conf.yaml:/dynamic_conf.yaml"
          - "{{ config_directory }}/plugins-storage:/plugins-storage"

          - "{{ config_directory }}/logs:/var/log/traefik"
        homepage:
          group: Networking
          weight: 300
          description: "Reverse proxy"
          widget:
            username: "{{ htpasswd.username }}"
            password: "{{ htpasswd.password }}"

    - name: Create logrotate container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        container_name: "{{ application }}-logrotate"
        image: ghcr.io/vegardit/traefik-logrotate:latest@sha256:a1dda881ae7c4d0ec1a862d87360aea125460775f8e804b5c0519d875d58d5fb
        env:
          TZ: "{{ common_timezone }}"

          LOGROTATE_LOGS: "/var/log/traefik/*.log"
          LOGROTATE_TRIGGER_INTERVAL: daily
          LOGROTATE_TRIGGER_SIZE: "1M"
          LOGROTATE_MAX_BACKUPS: "5"
          LOGROTATE_START_INDEX: "1"
          CRON_SCHEDULE: "* * * * *"
          CRON_LOG_LEVEL: "8"

          TRAEFIK_CONTAINER_ID_COMMAND: docker ps --no-trunc --quiet --filter label=org.opencontainers.image.title=Traefik
        volumes:
          - /run/podman/podman.sock:/var/run/docker.sock # required to send USR1 signal to Traefik after log rotation
          - "{{ config_directory }}/logs:/var/log/traefik"
