---

- hosts: homeserver

  vars:
    application: unifi

    container_network: "{{ networks.mgmt }}"

  tasks:
    - name: Create folders
      ansible.builtin.file:
        path: "{{ config_directory }}/{{ item }}"
        state: directory
        owner: "{{ common_user_id }}"
        group: "{{ common_group_id }}"
        mode: "0771"
      loop:
        - data
        - etc-rabbitmq-ssl
        - persistent
        - srv
        - var-lib-mongodb
        - var-lib-unifi
        - var-log

    - name: Create mongodb container
      ansible.builtin.include_role:
        name: mongodb
      vars:
        mongo_version: 8.3.7
        mongo_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32396237343434346238646361633439393832366461343465616161373862633265613231343033
          3435376538626533393863373331323335316230623566320a623166613433656566353163353265
          34333363656236303163623064653035333233653932636131393062363232646434666439373230
          6461306334356264630a393937393363363036633265306361663933316266376532633339303130
          30363464616562666439326662343034636630663239313937623438633333663765
        mongo_command: --logpath /dev/null --quiet

    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: ghcr.io/lemker/unifi-os-server:v1.4.0
        ip: "{{ container_network.subnet | ansible.utils.nthhost(31) }}"
        cgroupns: host
        cap_add:
          - NET_RAW
          - NET_ADMIN
        env:
          UOS_SYSTEM_IP: "{{ application }}.{{ common_local_tld }}"
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
          - "{{ config_directory }}/persistent:/persistent"
          - "{{ config_directory }}/var-log:/var/log"
          - "{{ config_directory }}/data:/data"
          - "{{ config_directory }}/srv:/srv"
          - "{{ config_directory }}/var-lib-unifi:/var/lib/unifi"
          - "{{ config_directory }}/var-lib-mongodb:/var/lib/mongodb"
          - "{{ config_directory }}/etc-rabbitmq-ssl:/etc/rabbitmq/ssl"
        tmpfs:
          /run: rw,exec
          /run/lock: rw
          /tmp: rw,exec
          /var/lib/journal: rw
          /var/opt/unifi/tmp: rw,size=64m
        homepage:
          name: UniFi OS
          group: Networking
          weight: 400
          description: "Manage UniFi devices"
          href: "https://{{ application }}.{{ common_local_tld }}"
