---

- hosts: homeserver

  vars:
    application: whodb

    container_network: "{{ networks.pub }}"

  tasks:
    - name: Create container
      ansible.builtin.include_role:
        name: podman_container
      vars:
        image: docker.io/clidey/whodb:0.130.0
        env:
          WHODB_ANTHROPIC_NAME: "{{ ai_provider }}"
          WHODB_ANTHROPIC_ENDPOINT: "{{ ai_base_url }}"
          WHODB_ANTHROPIC_API_KEY: "{{ ai_api_key }}"
        tmpfs:
          /data: rw,mode=0700
        traefik:
          - port: 8080
            auth: page
        homepage:
          name: WhoDB
          group: Remote Access
          weight: 600
          description: Database Management
